max_velocity = 1.0 #m/s
max_acceleration = 1.0 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    x = 1.0
    y = 1.0
    angle = 0.0
[end_pose]
    x = 3.519
    y = 1.515
    angle = 180.0

[[internal_points]]
    x = 2.976
    y = 2.256

[[internal_points]]
    x = 4.581
    y = 3.960

[[internal_points]]
    x = 3.618
    y = 6.233

[[internal_points]]
    x = 6.088
    y = 6.529

[[internal_points]]
    x = 7.175
    y = 1.910
