max_velocity = 1.0 #m/s
max_acceleration = 1.0 #m/s
start_velocity = 0.0 #m/s
end_velocity = 0.0 #m/s 
is_reversed = false
target_yaw = 0.0 #degrees

[start_pose]
    x = 1.47
    y = 6.275
    angle = 0.0
[end_pose]
    x = 8.270494
    y = 7.457694
    angle = 0.0

[[internal_points]]
    x = 3.421
    y = 6.405